### ISSUE TITLE
Tests fail on nightly

### ISSUE THREAD

**Issue by Manishearth** [tromey/gdb#30] opened 2016-04-22 18:23 UTC
They pass on 1.8 stable, but are broken on nightly:

```
FAIL: gdb.rust/simple.exp: print j
FAIL: gdb.rust/simple.exp: ptype j
FAIL: gdb.rust/simple.exp: print simple::Unit
FAIL: gdb.rust/simple.exp: print z
FAIL: gdb.rust/simple.exp: ptype z (pattern 1)
FAIL: gdb.rust/simple.exp: print simple::ByeBob(0xff, 5)
Running /home/manishearth/Mozilla/Git/gdb/gdb/testsuite/gdb.rust/expr.exp ...
Running /home/manishearth/Mozilla/Git/gdb/gdb/testsuite/gdb.rust/methods.exp ...
FAIL: gdb.rust/methods.exp: print x.take()
FAIL: gdb.rust/methods.exp: print *(x.incr())
FAIL: gdb.rust/methods.exp: print *((&mut x).incr())
```

```
print j
$4 = simple::Unit::Unit
(gdb) FAIL: gdb.rust/simple.exp: print j
ptype j
type = struct simple::Unit::Unit
(gdb) FAIL: gdb.rust/simple.exp: ptype j
print simple::Unit
No symbol 'simple::Unit' in current context
(gdb) FAIL: gdb.rust/simple.exp: print simple::Unit

print z
$13 = simple::ByeBob::ByeBob (7, 8)
(gdb) FAIL: gdb.rust/simple.exp: print z
gdb_expect_list pattern: / = struct simple::ByeBob \(/
ptype z
type = struct simple::ByeBob::ByeBob (
  i32,
  u64,
)
(gdb) FAIL: gdb.rust/simple.exp: ptype z (pattern 1)


print x.take()
could not find function named 'methods::HasMethods::take'
(gdb) FAIL: gdb.rust/methods.exp: print x.take()
print *(x.incr())
could not find function named 'methods::HasMethods::incr'
(gdb) FAIL: gdb.rust/methods.exp: print *(x.incr())
print *((&mut x).incr())
could not find function named 'methods::HasMethods::incr'
(gdb) FAIL: gdb.rust/methods.exp: print *((&mut x).incr())

info functions HasMethods::new
All functions matching regular expression "HasMethods::new":
(gdb) FAIL: gdb.rust/methods.exp: info functions HasMethods::new

```

I think the way paths work have changed, with some `{{impl}}` stuff and some extra namespacing

**Comment by tromey** [comment] 2016-04-25 04:44
I tried this and from my POV these are debuginfo regressions in nightly.  I filed bugs.  If it turns out that these were intentional changes then I suppose we can find a way to work around them.

**Comment by tromey** [comment] 2016-04-26 02:55
Going to close this, it seems those are real bugs in nightly.

**Closed as completed by tromey** 2016-04-26 02:55 UTC
Labels: rust
